# ==============================
# Configuración del servidor
# ==============================
spring:
  application:
    name: data-management-cache
  r2dbc:
    url: r2dbc:mssql://giia.database.windows.net:1433/giia_db?encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
    username: adminsql
    password: giia2025*
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  data:
    redis:
      host: giia-redis.redis.cache.windows.net
      port: 6380
      password: xbum3k1j93TXRMdmScdKTc6jXSkr0MpcGAzCaCe5rKQ=
server:
  port: 8080

# ==============================
# Configuración personalizada
# ==============================
datacache:
  redis:
    key-prefix:
      proveedor: "proveedor:"
      usuario-proveedor: "usuario-proveedor:"
      remision: "remision:"
      remision-material: "rem-mat:"
      material: "material:"
      inventario: "inventario:"
    channel:
      proveedor: "proveedor-updates"
      usuario-proveedor: "usu-proveedor-updates"
      remision: "remision-updates"
      material: "material-updates"
      inventario: "inventario-updates"
# ==============================
# Logging
# ==============================
logging:
  level:
    com.giia.datamanagement: DEBUG
    org.springframework.data.redis: INFO
    com.tuempresa.datamanagementcache: DEBUG
